### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by Elildar**

### CODE REVIEW

**Comment by laserloui** [comment]
Thanks! Are you 100% certain that unit names are correct? I've double checked Visceralus and according to this video (https://youtu.be/D2elA_MukXk?t=16), the spelling is correct. (your commit changes it to "Viscéralus").

**Comment by laserloui** [comment]
Also according to this video (https://youtu.be/zvON35Wyl7o?t=152), Skurge serrenox is correct. (your commit changes it to "Skurge Serrenox"). It's really important to be 100% certain about these things. I cannot double check everything :)

**Comment by laserloui** [comment]
Also, according to this video (https://youtu.be/7_u2yqPRErQ?t=126) Superquake is called "Super séisme" and not "Super-tremblement".

**Comment by laserloui** [comment]
I've added most of your translations. Thanks!

**Comment by Elildar** [comment]
No, these changes was not checked ingame. I have just translated with french logic and the pronunciation we have. It seem I don't have the same logic than Wildstar's translator. I will verify it soon, but I think your findings are better.
Which texts do you need to be 100% accurate?

**Comment by laserloui** [comment]
At the moment, only these translations are missing:

Shredder
["unit.bilious_brute"] = "Bilious Brute"
["datachron.shredder_jammed"] = "Ye've jammed me shredder, ye have! Blast ye filthy bilge slanks!"

Thrag (Miniboss)
["unit.bomb"] = "Jumpstart Charge"
["cast.gigavolt"] = "Gigavolt"

Maelstrom
["cast.shatter"] = "Shatter"

All these strings need to be 100% accurate.
The "jammed" message appears when the shredder midphase ends in the chat - NPC_Say.


2016-11-21 9:41 GMT+01:00 Elildar <notifications@github.com>:

**Comment by Elildar** [comment]
Maelstrom
["cast.shatter"] = "Fracasser"
is 100% accurate

For the others, I can't be certain about RMT translations because my new guild Wildcorp is not raiding RMT. Do you think I could join 1 Bloodpact pull on Shredder to see the french names? Or do you have another idea?

I will check for french videos about DS as soon as I can, but there is no RMT french videos.

**Pull request closed without merging**
