### PR TITLE
Shave off milliseconds here and there

### PR DESCRIPTION
**Pull request by vapourismo**
Slight performance upgrade, remove redundant code and restructure it a bit.

Needs review of [LUI_BossMods:SearchForEncounter](https://github.com/vapourismo/LUI-BossMods/blob/82fbceceb29c0bbf8decb0c3be7564a411144ff0/LUI_BossMods.lua#L283) since I am not sure how the restructure affects semantics. Works for me, tho.

PS: If you intend to merge this, actually merge it - don't just copy it :laughing:

### CODE REVIEW

**Comment by laserloui** [comment]
thanks a lot!

**Comment by laserloui** [comment]
gonna take a closer look at it tonight after we are done raiding.

**Comment by laserloui** [comment]
Thanks, i applied most of the changes.

I was not able to make sense of your logic in 'SearchForEncounter' but i agree, that my previous approach was pretty messy, so i reworked it completely. Should be much better now. Pls dont hesitate to make another push request if you can optimize it even further.

PS: i am not merging push requests since i am new to git and scared of stuff like that. So i usually take a very close look at all the changes and apply them manually one after another. Hope you don't mind.

**Comment by vapourismo** [comment]
I absolutely don't mind since I was in this position myself once. 

I recommend that you read up, on how git sub-commands `checkout`, `pull`, `merge` and `rebase` can be utilized. So it can save your ass sooner that later 😄 

PS: It's me, Vapou.

**Pull request closed without merging**
