### PR TITLE
DS: Gloomclaw

### PR DESCRIPTION
**Pull request by Mischh**
- Reopened with new branch without conflicts. -

Hey there!

Did it quite different than RaidCore. In particular I tried to make the Rupture timer more accurate.

Missing a important French Localization to make this work on Frech Clients (Burrow).

-Mischh

### CODE REVIEW

**Comment by laserloui** [comment]
thanks! i am finally ready to put in all the DS encounter modules. I will take a look at your push within the next days.

**Comment by laserloui** [comment]
Thanks! I've made only minor changes and added the rupture timer to the start of the fight.
Gonna test it out on Monday.

**Comment by Mischh** [comment]
you dont need no Rupture Timer at the start, because he starts with a burrow. The first Timer will start about 2 seconds after Pull, because Burrow ends.

**Comment by laserloui** [comment]
ahh ok, i totally forgot about this :)

**Pull request closed without merging**
