### PR TITLE
DS WaterFire: Localizations, Bomb Icons, Line to other Bombs

### PR DESCRIPTION
**Pull request by Mischh**
Hey there!

Just added the Localizations, which were missing, Added Icons(Sprites to be exact) to everyone having a Bomb on themselves and drew Lines between you and all of the other bomb-types, if you have got a bomb on yourself.

One thing i had a real problem with: Icons.
Seems these 'WorldFixedWindow'-things are not supposed to be shown, if occluded. For me, it did not update its position, if occluded. Which resulted in very weird placements. This may need a very close look.

When to prefer these over Pixies?

Btw: Are you aware, the parameter 'nHeight' in :DrawIcon() should be a Enum to choose where to anchor the Icon? (0=feet, 1=head, didnt research more - but 20 results in feet)

-Mischh

### CODE REVIEW

**Comment by laserloui** [comment]
Fixed the nHeight problem. Added nOffset and bTop instead. 

Icons are always better than pixies. I removed DrawPixie completely since there was no reason to use them over icons. Icons are much more versatile and the biggest advantage is: you don't have to update/redraw them.

Pixies are the main reason why bossmods use so much resources. you have to redraw them every frame as soon as their position or your viewport changes. Its a huge mess. On top of that, you are pretty limited with what you can display as a pixie. 

WorldFixedWindow on the other hand is bound to a specific location or unit and does not need further updates. No matter if the unit moves or your viewport changes, everything is getting updated automatically and you can put whatever you want into the window container. progress bars, icons, text... it doesnt matter. You can also access, edit and delete them super easily.

You can enable/disable occlusion, but i think it should be disabled by default. (not 100% sure)

**Comment by laserloui** [comment]
I am gonna cherry pick some things from your Fire/Water encounter module and put it together with some of my own stuff. I think the lines to all players with the opposite debuff are not really necessary and kinda "too much". 

Thanks as always.

PS: i will finish DS encounters this weekend, which means that the last thing left to do is to add quite a few german localizations to RMT/DS modules. You would do me a great favor if you could take a look at them.

**Comment by Mischh** [comment]
Ehm okay. I agree on the useability and easiness of WorldFixedWindows, but cant really argue around Resources, because I have no data for that. The occlusion part interests me tho. Do you know where to find this Option? Isnt it a global setting then? Wouldnt this interfer with settings in your Nameplates? (as example - i'm assuming most of them should use the same type of Window)

Its your chioce on the 'Lines to opposite Bomb', but wouldnt that be the perfect opportunity to say 'enabled=false' in the configs?

I cant really translate RMT modules, scince I only have access to the first Mini&Shredder. There is no way of confirming anything. But i can copy from RaidCore xD. 
DS I will translate, but i will not create any Pull Requests, if I did not yet have a chance to test them (this applies mostly to the Pairs)

As a side note: I have a update for the Earth/Logic pair, which predicts the Snakes movement to its current target. As you just mentioned the Bomb-Lines to be overkill, do you even want me to create a Pull Request for that? (Its currently written in the EncounterPrototypes style, i didn't yet translate it back.)

-Mischh

**Comment by laserloui** [comment]
just create a couple of pixies and update them every frame due to change in position / viewport. You will see the outrages amount of milliseconds it will cost. I already optimized the process so it will only get redrawn if position/viewport actually changed compared to the last frame and/or limit it to 25fps and so on, but there is little you can do. This whole thing is just terrible expensive.

When you look at WorldFixedWindow in Houston you can see "IsOccluded" and "IsOnScreen" functionality. I already use IsOnScreen to show/hide auras accordingly. 

```
if tDraw.wnd:IsOnScreen() then
    if not tDraw.wnd:IsShown() then
        tDraw.wnd:Show(true,true)
    end
else
    if tDraw.wnd:IsShown() then
        tDraw.wnd:Show(false,true)
    end
end`
```

About the Lines to opposite bombs... i just think it adds too much fluff to the module. There is really no need for stuff like this, same for the snake movement or avatus gun grids and so on (gun grid is a also a perfect example of how bad pixies are. updating/redrawing so many pixies will let your fps drop to zero).

I would really like to keep it clean and simple for GA/DS. We can do all the crazy, and optional stuff for RMT of course :)

**Pull request closed without merging**
