### PR TITLE
Some Contributions.

### PR DESCRIPTION
**Pull request by Mischh**
Hey! I saw the Addon 2 days ago on Curse and I love you for doing this!
I translated RaidCore for my Guild to German without even using it. (Because of performance issues). I actually thought about doing my own bossmod and then this addon appears.
This is what i did:
- Implemented a good chunk of Water/Fire-Pair (basically to try out how to write an encounter)
- Translated Shredder to German (and obviously the Pair)
- Added a Background to the Unlocked Frames . I dont know if there are Backgrounds for you (Screenshots on Curse), but for me there werent.
- Fixed a problem when tracked casts would be interrupted (instantly changed from Cast to MOO, but didnt check if the cast was tracked - would never hide the castbar, unless the tracked cast changes)

You probably want to look at the bottom of the Fire/Water-Pair. I really dont know if you like this. Please tell me if you want me to change it, to look like the other encounters.

-Mischh

### CODE REVIEW

**Comment by laserloui** [comment]
Thanks! Gonna take a closer lookt at it asap!

**Review by laserloui — COMMENTED** [review]
Unlocked Frames already have "LUI_BossMods:bg" as sprite by default. That is why i only toggle the Picture Style.

**Review by laserloui — COMMENTED** [review]
I really like your idea of using Helper Methods at boss modules so clean up the code. 👍

**Comment by Mischh** [comment]
If you liked the Helper Methods, i will take it a step further - be prepared for another pull request.

**Comment by laserloui** [comment]
You mean adding some sort of Prototype Module beforehand? Would be nice, since copying the helpers into every boss module would be really bad.

**Comment by Mischh** [comment]
Yes, Thats the Idea.

**Comment by Mischh** [comment]
I Will close this Pull request, scince i now will try to get my repository back in sync with yours and i dont want you to merge it after thats done.

**Pull request closed without merging**
