### PR TITLE
Encounter Prototype

### PR DESCRIPTION
**Pull request by Mischh**
Hey!

It took me some time, but here is what i thought about at the end of my last Pull Request.
- Added 'Encounters/EncounterPrototype.lua' with one publicly available Method LUI_BossMod:EncounterPrototype(EncounterName)
- Implemented Air/Water-Pair as demonstration of this EncounterPrototype.
- Added dummy_EncounterPrototype.lua to provide information about anything you may want to do with this.

One thing i really disliked the last time: Please do not just Copy&Paste - This just makes my life harder. (And the List of Commits longer and longer everytime.)

-Mischh

Edit: The Commits, which actually change anything are below the seven 'Revert XXX' (These reverts just revert all the changes i posted with the last pull request)

### CODE REVIEW

**Comment by laserloui** [comment]
Thanks! I'm gonna take a deep look at it as soon as i can. What do you mean with "Copy&Paste"? ... am i not supposed to put your changes into place and commit them? Since i am new to Git, i am open for suggestions.

**Comment by vapourismo** [comment]
``` sh
# Branch out using your current branch, new branch is called 'update-master'
git checkout -b update-master

# Apply the changes from Mischh's 'master' branch to 'update-master'
git pull "https://github.com/Mischh/LUI-BossMods.git" master

# If your master was ahead of Mischh's 'master', you'll need to rebase it so
# his changes are replayed ontop of yours
git rebase master

# Go back to your 'master' branch
git checkout master

# Merge the 'update-master' branch into 'master'
git merge update-master
```

If `rebase` or the merging from `pull` fail, you can abort the merge using `git merge --abort`.

**Comment by Zeffuro** [comment]
I'm relatively new to Git but using SmartGit makes a lot of this stuff easier. Also the Github site works nicely :)

**Comment by Mischh** [comment]
According to github it has now been 9 days, scince i opened this. Am i gonna get any kind of reaction? I mean, im fine to develop my own version for my guild, but i would at least like to know that i do.

**Comment by vapourismo** [comment]
@Mischh Keep in mind that you must not distribute exact or derived copies (as your hostile fork is) since @laserloui is the sole owner of this code. I suggest you properly rebase your mess, so it actually makes sense to merge it.

**Comment by Mischh** [comment]
Okay. It might have been a little bit of an aggressive comment on my side. Sorry. I will close this and figure out how to clean this up.

-Mischh

**Pull request closed without merging**
